# Distance in meters
rb_lidar_ignore_dist: 15.0
rb_max_speed: 3.0

# Stopping distances
rb_zero_cutoff: 8.0
rb_begin_stopping_dist: 50.0
rb_stop_sign_urgency: 0.6

# Rectangular region in front of the car (meters)
road_max_detect_dist: 100.0
road_min_detect_dist: 0.2
road_detect_width: 3

# Front lidar
front_max_detect_rad: 3.0
front_min_detect_rad: 0.5
denoise_threshold: 0.03
denoise_neighbors: 4
denoise_last_scan_thresh: 1.5
front_scan_range: 4.0
front_scan_width: 2.0
front_double_denoise: false

# Stop sign detection
sign_show_feed: false
sign_use_mask: false
sign_max_size: 160
sign_min_size: 20
sign_scale_factor: 1.1187
sign_min_neighbors: 9
sign_begin_stop_width: 28
sign_dilation_size: 30.0
sign_red_l_hue: 160
sign_red_l_sat: 179
sign_red_l_lum: 100
sign_red_h_hue: 179
sign_red_h_sat: 179
sign_red_h_lum: 255

sign_frame_count_trigger: 5
